# Generated by Django 4.1 on 2022-11-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socmapp', '0002_alter_appoinment_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='date',
            field=models.DateField(),
        ),
    ]
